server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: blog-config-server
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: ${CONFIG_DEFAULT_LABEL}
          search-paths: ${CONFIG_SEARCH_PATHS}
