server:
  port: 8888

spring:
  application:
    name: blog-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: ${CONFIG_DEFAULT_LABEL}
          search-paths: ${CONFIG_SEARCH_PATHS}

